# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word_eng', models.CharField(max_length=200)),
                ('Word_pol', models.CharField(max_length=200)),
                ('word_level', models.IntegerField(default=0)),
            ],
        ),
    ]
