# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='Word_eng',
            new_name='word_eng',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='Word_pol',
            new_name='word_pol',
        ),
    ]
